name: Update Lotto Folder

on:
  schedule:
    - cron: '0 0 3,18 * *'  # 00:00 UTC on the 2nd and 17th
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install adm-zip

      - name: Update lottonumbers folder
        run: node updateLottoFolder.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lottonumbers
          git commit -m "Update lottonumbers folder" || echo "No changes to commit"
          git push
